/* Additional Binance / TradingView indicator catalog */
const INDICATOR_REGISTRY_EXTRA = [
  { id: 'avl', baseName: 'AVL', group: '메인', type: 'overlay',
    defaults: { period: 20, color: '#f7931a', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 1, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.avl(c, p.period) },
  { id: 'vwap', baseName: 'VWAP', group: '메인', type: 'overlay',
    defaults: { color: '#e040fb', lineWidth: 2 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.vwap(c) },
  { id: 'hma', baseName: 'HMA', group: '메인', type: 'overlay',
    defaults: { period: 20, color: '#00e676', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.hma(c, p.period) },
  { id: 'trima', baseName: 'TRIMA', group: '메인', type: 'overlay',
    defaults: { period: 20, color: '#ff6d00', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.trima(c, p.period) },
  { id: 'kc', baseName: 'KC', group: '메인', type: 'overlay-band',
    defaults: { period: 20, mult: 2, color: '#26c6da', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'mult', label: 'ATR 배수', type: 'number', min: 0.5, max: 5, step: 0.1 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.keltner(c, p.period, p.mult) },
  { id: 'dc', baseName: 'DC', group: '메인', type: 'overlay-band',
    defaults: { period: 20, color: '#7e57c2', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.donchian(c, p.period) },
  { id: 'ichimoku', baseName: 'Ichimoku', group: '메인', type: 'overlay-multi',
    defaults: { tenkan: 9, kijun: 26, senkou: 52, lineWidth: 1,
      colorTenkan: '#2962ff', colorKijun: '#f7931a', colorSenkouA: '#26a69a', colorSenkouB: '#ef5350',
      colorChikou: '#787b86' },
    params: [
      { key: 'tenkan', label: '전환선', type: 'number', min: 1, max: 100 },
      { key: 'kijun', label: '기준선', type: 'number', min: 1, max: 200 },
      { key: 'senkou', label: '선행스팬B', type: 'number', min: 1, max: 300 },
      { key: 'colorTenkan', label: '전환선 색', type: 'color' },
      { key: 'colorKijun', label: '기준선 색', type: 'color' },
      { key: 'colorSenkouA', label: '선행A 색', type: 'color' },
      { key: 'colorSenkouB', label: '선행B 색', type: 'color' },
      { key: 'colorChikou', label: '후행스팬 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [
      { key: 'tenkan', colorParam: 'colorTenkan' },
      { key: 'kijun', colorParam: 'colorKijun' },
      { key: 'senkouA', colorParam: 'colorSenkouA' },
      { key: 'senkouB', colorParam: 'colorSenkouB' },
      { key: 'chikou', colorParam: 'colorChikou' },
    ],
    compute: (c, p) => TA.ichimoku(c, p.tenkan, p.kijun, p.senkou) },
  { id: 'mike', baseName: 'MIKE', group: '메인', type: 'overlay-multi',
    defaults: { period: 12, lineWidth: 1,
      colorWr: '#ef5350', colorMr: '#f7931a', colorSr: '#ffeb3b',
      colorWs: '#26a69a', colorMs: '#2962ff', colorSs: '#9c27b0' },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'colorWr', label: 'WR 색', type: 'color' },
      { key: 'colorMr', label: 'MR 색', type: 'color' },
      { key: 'colorSr', label: 'SR 색', type: 'color' },
      { key: 'colorWs', label: 'WS 색', type: 'color' },
      { key: 'colorMs', label: 'MS 색', type: 'color' },
      { key: 'colorSs', label: 'SS 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [
      { key: 'wr', colorParam: 'colorWr' }, { key: 'mr', colorParam: 'colorMr' }, { key: 'sr', colorParam: 'colorSr' },
      { key: 'ws', colorParam: 'colorWs' }, { key: 'ms', colorParam: 'colorMs' }, { key: 'ss', colorParam: 'colorSs' },
    ],
    compute: (c, p) => TA.mike(c, p.period) },
  { id: 'pbx', baseName: 'PBX', group: '메인', type: 'overlay-multi',
    defaults: { lineWidth: 1, colorE4: '#ff5252', colorE6: '#ff9800', colorE9: '#ffeb3b',
      colorE13: '#4caf50', colorE18: '#2196f3', colorE24: '#9c27b0' },
    params: [
      { key: 'colorE4', label: 'EMA4 색', type: 'color' },
      { key: 'colorE6', label: 'EMA6 색', type: 'color' },
      { key: 'colorE9', label: 'EMA9 색', type: 'color' },
      { key: 'colorE13', label: 'EMA13 색', type: 'color' },
      { key: 'colorE18', label: 'EMA18 색', type: 'color' },
      { key: 'colorE24', label: 'EMA24 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [
      { key: 'e4', colorParam: 'colorE4' }, { key: 'e6', colorParam: 'colorE6' }, { key: 'e9', colorParam: 'colorE9' },
      { key: 'e13', colorParam: 'colorE13' }, { key: 'e18', colorParam: 'colorE18' }, { key: 'e24', colorParam: 'colorE24' },
    ],
    compute: (c) => TA.pbx(c) },
  { id: 'trix', baseName: 'TRIX', group: '서브', type: 'sub-line',
    defaults: { period: 12, color: '#ab47bc', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.trix(c, p.period) },
  { id: 'dma', baseName: 'DMA', group: '서브', type: 'sub-multi',
    defaults: { short: 10, long: 50, m: 10, colorDma: '#2962ff', colorAma: '#f7931a', lineWidth: 1 },
    params: [
      { key: 'short', label: '단기', type: 'number', min: 1, max: 100 },
      { key: 'long', label: '장기', type: 'number', min: 1, max: 300 },
      { key: 'm', label: 'AMA', type: 'number', min: 1, max: 100 },
      { key: 'colorDma', label: 'DMA 색', type: 'color' },
      { key: 'colorAma', label: 'AMA 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [{ key: 'dma', colorParam: 'colorDma' }, { key: 'ama', colorParam: 'colorAma' }],
    compute: (c, p) => TA.dma(c, p.short, p.long, p.m) },
  { id: 'dpo', baseName: 'DPO', group: '서브', type: 'sub-line',
    defaults: { period: 20, color: '#5c6bc0', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.dpo(c, p.period) },
  { id: 'cr', baseName: 'CR', group: '서브', type: 'sub-multi',
    defaults: { period: 26, m: 10, colorCr: '#ef5350', colorMa: '#f7931a', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'm', label: 'MA', type: 'number', min: 1, max: 100 },
      { key: 'colorCr', label: 'CR 색', type: 'color' },
      { key: 'colorMa', label: 'MA 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [{ key: 'cr', colorParam: 'colorCr' }, { key: 'ma', colorParam: 'colorMa' }],
    compute: (c, p) => TA.cr(c, p.period, p.m) },
  { id: 'brar', baseName: 'BRAR', group: '서브', type: 'sub-multi',
    defaults: { period: 26, colorAr: '#26a69a', colorBr: '#ef5350', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'colorAr', label: 'AR 색', type: 'color' },
      { key: 'colorBr', label: 'BR 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [{ key: 'ar', colorParam: 'colorAr' }, { key: 'br', colorParam: 'colorBr' }],
    compute: (c, p) => TA.brar(c, p.period) },
  { id: 'asi', baseName: 'ASI', group: '서브', type: 'sub-multi',
    defaults: { m: 6, colorAsi: '#7e57c2', colorMa: '#f7931a', lineWidth: 1 },
    params: [
      { key: 'm', label: 'MA', type: 'number', min: 1, max: 100 },
      { key: 'colorAsi', label: 'ASI 색', type: 'color' },
      { key: 'colorMa', label: 'MA 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [{ key: 'asi', colorParam: 'colorAsi' }, { key: 'ma', colorParam: 'colorMa' }],
    compute: (c, p) => TA.asi(c, p.m) },
  { id: 'wvad', baseName: 'WVAD', group: '서브', type: 'sub-line',
    defaults: { color: '#00897b', lineWidth: 1 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.wvad(c) },
  { id: 'ad', baseName: 'AD', group: '서브', type: 'sub-line',
    defaults: { color: '#3949ab', lineWidth: 1 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.ad(c) },
  { id: 'cmf', baseName: 'CMF', group: '서브', type: 'sub-line',
    defaults: { period: 20, color: '#6d4c41', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.cmf(c, p.period) },
  { id: 'cho', baseName: 'CHO', group: '서브', type: 'sub-line',
    defaults: { fast: 3, slow: 10, color: '#8e24aa', lineWidth: 1 },
    params: [
      { key: 'fast', label: 'Fast', type: 'number', min: 1, max: 50 },
      { key: 'slow', label: 'Slow', type: 'number', min: 1, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.cho(c, p.fast, p.slow) },
  { id: 'pvt', baseName: 'PVT', group: '서브', type: 'sub-line',
    defaults: { color: '#1e88e5', lineWidth: 1 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.pvt(c) },
  { id: 'vroc', baseName: 'VROC', group: '서브', type: 'sub-line',
    defaults: { period: 12, color: '#d81b60', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 1, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.vroc(c, p.period) },
  { id: 'cmo', baseName: 'CMO', group: '서브', type: 'sub-line',
    defaults: { period: 14, color: '#43a047', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.cmo(c, p.period) },
  { id: 'ppo', baseName: 'PPO', group: '서브', type: 'sub-line',
    defaults: { fast: 12, slow: 26, color: '#fb8c00', lineWidth: 1 },
    params: [
      { key: 'fast', label: 'Fast', type: 'number', min: 1, max: 100 },
      { key: 'slow', label: 'Slow', type: 'number', min: 1, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.ppo(c, p.fast, p.slow) },
  { id: 'uo', baseName: 'UO', group: '서브', type: 'sub-line',
    defaults: { p1: 7, p2: 14, p3: 28, color: '#00acc1', lineWidth: 1 },
    params: [
      { key: 'p1', label: '기간1', type: 'number', min: 1, max: 50 },
      { key: 'p2', label: '기간2', type: 'number', min: 1, max: 100 },
      { key: 'p3', label: '기간3', type: 'number', min: 1, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.uo(c, p.p1, p.p2, p.p3), range: [0, 100] },
  { id: 'aroon', baseName: 'Aroon', group: '서브', type: 'sub-multi',
    defaults: { period: 25, colorUp: '#26a69a', colorDown: '#ef5350', colorOsc: '#ffeb3b', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'colorUp', label: 'Up 색', type: 'color' },
      { key: 'colorDown', label: 'Down 색', type: 'color' },
      { key: 'colorOsc', label: 'Osc 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [
      { key: 'up', colorParam: 'colorUp' },
      { key: 'down', colorParam: 'colorDown' },
      { key: 'osc', colorParam: 'colorOsc' },
    ],
    compute: (c, p) => TA.aroon(c, p.period), range: [0, 100] },
  { id: 'stochrsi', baseName: 'StochRSI', group: '서브', type: 'sub-multi',
    defaults: { period: 14, k: 3, d: 3, colorK: '#5e35b1', colorD: '#f7931a', lineWidth: 1 },
    params: [
      { key: 'period', label: 'RSI 기간', type: 'number', min: 2, max: 100 },
      { key: 'k', label: '%K', type: 'number', min: 1, max: 50 },
      { key: 'd', label: '%D', type: 'number', min: 1, max: 50 },
      { key: 'colorK', label: '%K 색', type: 'color' },
      { key: 'colorD', label: '%D 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [{ key: 'k', colorParam: 'colorK' }, { key: 'd', colorParam: 'colorD' }],
    compute: (c, p) => TA.stochRsi(c, p.period, p.k, p.d), range: [0, 100] },
  { id: 'sroc', baseName: 'SROC', group: '서브', type: 'sub-line',
    defaults: { period: 13, smooth: 21, color: '#c0ca33', lineWidth: 1 },
    params: [
      { key: 'period', label: 'ROC 기간', type: 'number', min: 1, max: 100 },
      { key: 'smooth', label: 'Smooth', type: 'number', min: 1, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.sroc(c, p.period, p.smooth) },
  { id: 'mass', baseName: 'MASS', group: '서브', type: 'sub-line',
    defaults: { period: 9, color: '#6a1b9a', lineWidth: 1 },
    params: [
      { key: 'period', label: 'EMA 기간', type: 'number', min: 2, max: 50 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.mass(c, p.period) },
  { id: 'priceosc', baseName: 'PriceOsc', group: '서브', type: 'sub-line',
    defaults: { short: 12, long: 26, color: '#ff7043', lineWidth: 1 },
    params: [
      { key: 'short', label: '단기', type: 'number', min: 1, max: 100 },
      { key: 'long', label: '장기', type: 'number', min: 1, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.priceOsc(c, p.short, p.long) },
  { id: 'nvi', baseName: 'NVI', group: '서브', type: 'sub-line',
    defaults: { color: '#4527a0', lineWidth: 1 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.nvi(c) },
  { id: 'pvi', baseName: 'PVI', group: '서브', type: 'sub-line',
    defaults: { color: '#1565c0', lineWidth: 1 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.pvi(c) },
  { id: 'adtm', baseName: 'ADTM', group: '서브', type: 'sub-line',
    defaults: { period: 23, color: '#bf360c', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.adtm(c, p.period) },
  { id: 'tapi', baseName: 'TAPI', group: '서브', type: 'sub-line',
    defaults: { period: 6, color: '#558b2f', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 1, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.tapi(c, p.period) },
  { id: 'vwma', baseName: 'VWMA', group: '메인', type: 'overlay',
    defaults: { period: 20, color: '#ec407a', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 1, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.vwma(c, p.period) },
  { id: 'kama', baseName: 'KAMA', group: '메인', type: 'overlay',
    defaults: { period: 10, fast: 2, slow: 30, color: '#66bb6a', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'fast', label: 'Fast', type: 'number', min: 1, max: 50 },
      { key: 'slow', label: 'Slow', type: 'number', min: 1, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.kama(c, p.period, p.fast, p.slow) },
  { id: 'pivot', baseName: 'Pivot', group: '메인', type: 'overlay-multi',
    defaults: { lineWidth: 1, colorP: '#d1d4dc', colorR1: '#ef5350', colorS1: '#26a69a', colorR2: '#f7931a', colorS2: '#2962ff' },
    params: [
      { key: 'colorP', label: 'Pivot 색', type: 'color' },
      { key: 'colorR1', label: 'R1 색', type: 'color' },
      { key: 'colorS1', label: 'S1 색', type: 'color' },
      { key: 'colorR2', label: 'R2 색', type: 'color' },
      { key: 'colorS2', label: 'S2 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [
      { key: 'p', colorParam: 'colorP' }, { key: 'r1', colorParam: 'colorR1' }, { key: 's1', colorParam: 'colorS1' },
      { key: 'r2', colorParam: 'colorR2' }, { key: 's2', colorParam: 'colorS2' },
    ],
    compute: (c) => TA.pivotClassic(c) },
  { id: 'adx', baseName: 'ADX', group: '서브', type: 'sub-line',
    defaults: { period: 14, color: '#ffeb3b', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.adx(c, p.period), range: [0, 100] },
  { id: 'natr', baseName: 'NATR', group: '서브', type: 'sub-line',
    defaults: { period: 14, color: '#8d6e63', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.natr(c, p.period) },
  { id: 'trange', baseName: 'TRANGE', group: '서브', type: 'sub-line',
    defaults: { color: '#78909c', lineWidth: 1 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.trange(c) },
  { id: 'bop', baseName: 'BOP', group: '서브', type: 'sub-line',
    defaults: { color: '#7cb342', lineWidth: 1 },
    params: [
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c) => TA.bop(c) },
  { id: 'wad', baseName: 'WAD', group: '서브', type: 'sub-multi',
    defaults: { period: 20, colorWad: '#5c6bc0', colorMa: '#f7931a', lineWidth: 1 },
    params: [
      { key: 'period', label: 'MA', type: 'number', min: 1, max: 100 },
      { key: 'colorWad', label: 'WAD 색', type: 'color' },
      { key: 'colorMa', label: 'MA 색', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    lines: [{ key: 'wad', colorParam: 'colorWad' }, { key: 'ma', colorParam: 'colorMa' }],
    compute: (c, p) => TA.wad(c, p.period) },
  { id: 'mi', baseName: 'MI', group: '서브', type: 'sub-line',
    defaults: { period: 12, color: '#d4e157', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 1, max: 100 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.mi(c, p.period) },
  { id: 'rc', baseName: 'RC', group: '서브', type: 'sub-line',
    defaults: { period: 50, color: '#ff8a65', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 1, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.rc(c, p.period) },
  { id: 'stddev', baseName: 'StdDev', group: '서브', type: 'sub-line',
    defaults: { period: 20, color: '#ba68c8', lineWidth: 1 },
    params: [
      { key: 'period', label: '기간', type: 'number', min: 2, max: 200 },
      { key: 'color', label: '색상', type: 'color' },
      { key: 'lineWidth', label: '선 두께', type: 'number', min: 1, max: 4 },
    ],
    compute: (c, p) => TA.stdDev(c, p.period) },
];
